function yaw_vs_contrast_and_speed_fit(DATA)
    %CREATEFIT(DATA)
    %  Create a fit.
    %
    %  Data for 'Figure 2A' fit:
    %      X Input : Log10Contrast
    %      Y Input : Log10Speed
    %      Z Output: Yaw
    %      Weights : Weights
    %  Output:
    %      fitresult : a fit object representing the fit.
    %      gof : structure with goodness-of fit info.
    %
    %  See also FIT, CFIT, SFIT.
    
    
    %  Auto-generated by MATLAB on 13-Mar-2018 16:46:19
    
    %% Fit: 'Figure 2A'.
    
    
    DATA=dpxdSubset(DATA,strcmp(DATA.mouse,'MEAN'));
    
    Speed=DATA.speeds;
    Contrast=DATA.contrast;
    Yaw=DATA.yaw;
    Weights=1./DATA.yawSem;
    
    Log10Contrast=log10(Contrast);
    Log10Speed=log10(Speed);
    
    
    
    
    [xData, yData, zData, weights] = prepareSurfaceData( Log10Contrast, Log10Speed, Yaw, Weights );
    
    % Set up fittype and options.
    ft = fittype( 'poly22' );
    opts = fitoptions( 'Method', 'LinearLeastSquares' );
    opts.Weights = weights;
    
    % Fit model to data.
    [fitresult, gof] = fit( [xData, yData], zData, ft, opts );
    
    % Plot fit with data.
    figure( 'Name', 'Figure 2A' );
    h = plot( fitresult, [xData, yData], zData );
    legend( h, 'Figure 2A', 'Yaw vs. Log10Contrast, Log10Speed with Weights', 'Location', 'NorthEast' );
    % Label axes
    xlabel Log10 Contrast
    ylabel Log10 Speed (deg/s)
    zlabel Yaw
    grid on
    view( -0.7, 3.6 );

    keyboard
end
    
    
